console.group("Group1")
console.groupCollapsed("Child Group")
console.log("Message One")
console.log("Message Two")
console.groupCollapsed("Grand Child Group")
console.log("Message One")
console.log("Message Two")
console.groupEnd("Grand Child Group")
console.groupEnd("Child Group")
console.groupEnd("Group1")
console.group("Group2")
console.log("Message One")
console.log("Message Two")
console.groupEnd("Group2")
